// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/gossip.proto

package gossippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceEntry e' l'equivalente sul filo di registry.ServiceEntry.
type ServiceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Counter       uint64                 `protobuf:"varint,3,opt,name=counter,proto3" json:"counter,omitempty"`
	OwnerNodeId   string                 `protobuf:"bytes,4,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEntry) Reset() {
	*x = ServiceEntry{}
	mi := &file_proto_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEntry) ProtoMessage() {}

func (x *ServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEntry.ProtoReflect.Descriptor instead.
func (*ServiceEntry) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceEntry) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *ServiceEntry) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ServiceEntry) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *ServiceEntry) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

func (x *ServiceEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// PeerClaim e' l'equivalente sul filo di membership.PeerInfo: una
// dichiarazione di stato su un peer, versionata con lo stesso schema
// (counter, owner_node_id) di ServiceEntry, per poter confrontare in modo
// affidabile dichiarazioni discordanti ricevute da nodi diversi
// (last-write-wins) senza mai confrontare orologi fisici.
type PeerClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Counter       uint64                 `protobuf:"varint,2,opt,name=counter,proto3" json:"counter,omitempty"`
	OwnerNodeId   string                 `protobuf:"bytes,3,opt,name=owner_node_id,json=ownerNodeId,proto3" json:"owner_node_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerClaim) Reset() {
	*x = PeerClaim{}
	mi := &file_proto_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerClaim) ProtoMessage() {}

func (x *PeerClaim) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerClaim.ProtoReflect.Descriptor instead.
func (*PeerClaim) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *PeerClaim) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerClaim) GetCounter() uint64 {
	if x != nil {
		return x.Counter
	}
	return 0
}

func (x *PeerClaim) GetOwnerNodeId() string {
	if x != nil {
		return x.OwnerNodeId
	}
	return ""
}

func (x *PeerClaim) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// ExchangeRequest e' il "push": lo stato locale del nodo che inizia lo scambio.
type ExchangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderAddr    string                 `protobuf:"bytes,1,opt,name=sender_addr,json=senderAddr,proto3" json:"sender_addr,omitempty"`
	Entries       []*ServiceEntry        `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	PeerClaims    []*PeerClaim           `protobuf:"bytes,3,rep,name=peer_claims,json=peerClaims,proto3" json:"peer_claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_proto_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRequest) GetSenderAddr() string {
	if x != nil {
		return x.SenderAddr
	}
	return ""
}

func (x *ExchangeRequest) GetEntries() []*ServiceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ExchangeRequest) GetPeerClaims() []*PeerClaim {
	if x != nil {
		return x.PeerClaims
	}
	return nil
}

// ExchangeResponse e' il "pull": lo stato locale del nodo che risponde.
type ExchangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ServiceEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	PeerClaims    []*PeerClaim           `protobuf:"bytes,2,rep,name=peer_claims,json=peerClaims,proto3" json:"peer_claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_proto_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeResponse) GetEntries() []*ServiceEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ExchangeResponse) GetPeerClaims() []*PeerClaim {
	if x != nil {
		return x.PeerClaims
	}
	return nil
}

var File_proto_gossip_proto protoreflect.FileDescriptor

const file_proto_gossip_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gossip.proto\x12\x06gossip\"\x9f\x01\n" +
	"\fServiceEntry\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x18\n" +
	"\acounter\x18\x03 \x01(\x04R\acounter\x12\"\n" +
	"\rowner_node_id\x18\x04 \x01(\tR\vownerNodeId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"y\n" +
	"\tPeerClaim\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x18\n" +
	"\acounter\x18\x02 \x01(\x04R\acounter\x12\"\n" +
	"\rowner_node_id\x18\x03 \x01(\tR\vownerNodeId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\x96\x01\n" +
	"\x0fExchangeRequest\x12\x1f\n" +
	"\vsender_addr\x18\x01 \x01(\tR\n" +
	"senderAddr\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.gossip.ServiceEntryR\aentries\x122\n" +
	"\vpeer_claims\x18\x03 \x03(\v2\x11.gossip.PeerClaimR\n" +
	"peerClaims\"v\n" +
	"\x10ExchangeResponse\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.gossip.ServiceEntryR\aentries\x122\n" +
	"\vpeer_claims\x18\x02 \x03(\v2\x11.gossip.PeerClaimR\n" +
	"peerClaims2G\n" +
	"\x06Gossip\x12=\n" +
	"\bExchange\x12\x17.gossip.ExchangeRequest\x1a\x18.gossip.ExchangeResponseB$Z\"sdcc-b1-registry/internal/gossippbb\x06proto3"

var (
	file_proto_gossip_proto_rawDescOnce sync.Once
	file_proto_gossip_proto_rawDescData []byte
)

func file_proto_gossip_proto_rawDescGZIP() []byte {
	file_proto_gossip_proto_rawDescOnce.Do(func() {
		file_proto_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gossip_proto_rawDesc), len(file_proto_gossip_proto_rawDesc)))
	})
	return file_proto_gossip_proto_rawDescData
}

var file_proto_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gossip_proto_goTypes = []any{
	(*ServiceEntry)(nil),     // 0: gossip.ServiceEntry
	(*PeerClaim)(nil),        // 1: gossip.PeerClaim
	(*ExchangeRequest)(nil),  // 2: gossip.ExchangeRequest
	(*ExchangeResponse)(nil), // 3: gossip.ExchangeResponse
}
var file_proto_gossip_proto_depIdxs = []int32{
	0, // 0: gossip.ExchangeRequest.entries:type_name -> gossip.ServiceEntry
	1, // 1: gossip.ExchangeRequest.peer_claims:type_name -> gossip.PeerClaim
	0, // 2: gossip.ExchangeResponse.entries:type_name -> gossip.ServiceEntry
	1, // 3: gossip.ExchangeResponse.peer_claims:type_name -> gossip.PeerClaim
	2, // 4: gossip.Gossip.Exchange:input_type -> gossip.ExchangeRequest
	3, // 5: gossip.Gossip.Exchange:output_type -> gossip.ExchangeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_gossip_proto_init() }
func file_proto_gossip_proto_init() {
	if File_proto_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gossip_proto_rawDesc), len(file_proto_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gossip_proto_goTypes,
		DependencyIndexes: file_proto_gossip_proto_depIdxs,
		MessageInfos:      file_proto_gossip_proto_msgTypes,
	}.Build()
	File_proto_gossip_proto = out.File
	file_proto_gossip_proto_goTypes = nil
	file_proto_gossip_proto_depIdxs = nil
}
